server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://118.31.43.234/warmerblog?useSSL=false
    #url: jdbc:mysql://localhost/warmerblog?useSSL=false
    username: tan
    #username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    mode: HTML5
  http:
    encoding:
      charset: utf-8
    converters:
      preferred-json-mapper: jackson
  application:
    name: warmer
  redis:
    host: 127.0.0.1 #默认就是localhost
    port: 6379 #默认
    password: 
    Pool:
      maxActive: 100
      maxIdle: 10
      maxWait: 100000
    timeout: 0
  # rabbitMq
  rabbitmq:
    host: 127.0.0.1 #默认localhost
    port: 5672 #默认
    virtualHost: /
    publisher-confirms: true 
    queues: topic.1,helloQuene.*,helloQuene
    username: root
    password: root
  # rabbitMq
  # mail
  mail:
    default-encoding: UTF-8
    host: smtp.126.com
    #端口
    port: 25
    #协议
    protocol: smtp
    #发送者的邮箱账号
    username: warmercloud@126.com
    #发送者的邮箱授权码,非登录密码
    password: miracletan2018
  # mail
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  #config-location: classpath:mybatis-conf.xml
logging:
  config: classpath:logback.xml  
  level:
    root: info
#--------七牛云配置
qiniu:
  access:
    key: 2J5BOKpbxDlzkYVYZ5dwGS3jAevVmOJwcL3fIdpw
  secret:
    key: 2LXAQbFFbFR_I76bseNEmu-Sjnh4RRaSRsazX5Dj
  bucket:
    name: nndt
    host:
      name: file.miaoleyan.com
  prefixName: /nndt
#--------七牛云配置
img:  #//如果是Windows情况下，格式是 D:\\blog\\image   linx 格式"/home/blog/image";
   location : D:\\blog\\image
#--------极验验证码配置
geetest:
  geetest_id: 86cc24901b72dce49d347561a548a84e
  geetest_key: 08c31f60e8eed5e48a9ebd12d0ba1027
  newfailback: true
#--------极验验证码配置
# Elasticsearch 6.3版本
elasticsearch:
  ip: 127.0.0.1
  port: 9300
  cluster:
    name: elasticsearch
  pool: 5
# Elasticsearch

