server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/warmerblog?useSSL=false
    username: #你的mysql用户名
    password: #密码
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    mode: HTML5
  neo4j:
      url: #你的neo4j 数据库连接 bolt://xxx.xxx.xxx.xxx:7687
      username: #用户名
      password: #密码
  http:
    encoding:
      charset: utf-8
    converters:
      preferred-json-mapper: jackson
  servlet:
    multipart:
      max-file-size: 100Mb
      max-request-size: 1000Mb
  application:
    name: warmer
  #redis
  redis:
    # Redis服务器地址
    host: #你的redis  ip #默认就是localhost
    #host: localhost
    # Redis服务器连接端口
    port: 6379 #默认
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器连接密码（默认为空）
    password:  #你的redis密码
    # 连接超时时间（毫秒）
    timeout: 10000
    # Lettuce
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 10000
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
      # 关闭超时时间
      shutdown-timeout: 100
  # rabbitMq
  rabbitmq:
    host: 127.0.0.1 #默认localhost
    port: 5672 #默认
    virtualHost: /
    publisher-confirms: true
    queues: topic.1,helloQuene.*,helloQuene
    username: root
    password: root
  # rabbitMq
  # mail
  mail:
    default-encoding: UTF-8
    host: smtp.126.com
    #端口
    port: 25
    #协议
    protocol: smtp
    #发送者的邮箱账号
    username: #你的账号
    #发送者的邮箱授权码,非登录密码
    password: #你的密码
  # mail
mybatis:
  mapper-locations: classpath*:mapper/*.xml
logging:
  config: classpath:logback-spring.xml
  level:
    root: error
#--------七牛云配置
qiniu:
  access:
    key: #你的access.key
  secret:
    key: #你的secret.key
  bucket:
    name: #你的bucket.name
    host:
      name: #你的七牛云域名
  prefixName: /nndt
#--------七牛云配置
img:  #//如果是Windows情况下，格式是 D:\\blog\\image   linx 格式"/home/blog/image";
   location : D:\\blog\\image
file:
  serverurl:  http://localhost:8089
  location : D:\\kgmanager\\csv   #如果是Windows情况下，格式是 D:\\kgmanager\\csv   linx 格式"/home/kgmanager/csv";
#--------极验验证码配置
geetest:
  geetest_id: #你的及验验证码id
  geetest_key: #你的key
  newfailback: true
#--------极验验证码配置
# Elasticsearch 6.3版本
elasticsearch:
  ip: 127.0.0.1
  port: 9300
  cluster:
    name: elasticsearch
  pool: 5
# Elasticsearch
github:
  client:
    clientId: #你的id
    clientSecret: #你的secret
    accessTokenUri: https://github.com/login/oauth/access_token
    userAuthorizationUri: https://github.com/login/oauth/authorize
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://api.github.com/user

